### ISSUE TITLE
API isn't working!

### ISSUE THREAD

**Issue by Dylan3304** [boxbilling/boxbilling#317]
Hello,
I've been trying to use the BoxBilling API for a quite a long time now. I'm using the latest version, `4.13.2` I believe. **I have been getting the following error:**
```
Fatal error: Uncaught exception 'Exception' with message 'Curl Error: ""' in path/BoxBillingApi.php:100 Stack trace: #0 path/support.php(32): Service_BoxBilling->__call('system_version', Array) #1 path/support.php(32): Service_BoxBilling->system_version() #2 {main} thrown in path/BoxBillingApi.php on line 100
```
My BoxBillingApi.php looks like this:
```
<?php
class Service_BoxBilling
{
    /**
     * Api URL
     *
     * @example https://www.boxbilling.com/api
     * @var string
     */
    protected $_api_url     = NULL;

    /**
     * Api Token found in BoxBilling profile page
     *
     * @example e4yny7yjy5u3yhyhepumuqaquva3y4as
     * @var string
     */
    protected $_api_token   = NULL;

    /**
     * Same service can be used to control BoxBilling as client and guest
     * 
     * @example guest
     * @example admin
     * @example client
     * @var string
     */
    protected $_api_role    = 'guest';

    /**
     * Path to cookie to save session for requests.
     * 
     * @var string - path to cookie. Must be writable 
     */
    protected $_cookie    = NULL;

    public function __construct($options)
    {
        if (!extension_loaded('curl')) {
            throw new Exception('cURL extension is not enabled');
        }
        
        if(isset($options['api_url'])) {
            $this->_api_url = $options['api_url'];
        }
        
        if(isset($options['api_role'])) {
            $this->_api_role = $options['api_role'];
        }

        if(isset($options['api_token'])) {
            $this->_api_token = $options['api_token'];
        }
        
        $this->_cookie = sys_get_temp_dir() . 'bbcookie.txt';
    }

    public function __call($method, $arguments)
    {
        $data = array();
        if(isset($arguments[0]) && is_array($arguments[0])) {
            $data = $arguments[0];
        }
        
        $module = substr($method, 0, strpos($method, '_'));
        $m      = substr($method, strpos($method, '_')+1);
        
        $url = $this->_api_url.'/'.$this->_api_role.'/'.$module.'/'.$m;

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,               $url);
        curl_setopt($ch, CURLOPT_HTTPAUTH,          CURLAUTH_BASIC) ;
        curl_setopt($ch, CURLOPT_REFERER,           $this->_api_url) ;
        curl_setopt($ch, CURLOPT_USERPWD,           $this->_api_role.":".$this->_api_token);
        curl_setopt($ch, CURLOPT_COOKIEJAR,         $this->_cookie);
        curl_setopt($ch, CURLOPT_COOKIEFILE,        $this->_cookie);
        curl_setopt($ch, CURLOPT_POST,              true);
        curl_setopt($ch, CURLOPT_POSTFIELDS,        http_build_query($data));
        curl_setopt($ch, CURLOPT_RETURNTRANSFER,    true);
        $result = curl_exec($ch);
        
        if($result === false) {
            $e = new Exception(sprintf('Curl Error: "%s"', curl_error($ch)));
            curl_close($ch);
            throw $e;
        }
        
        curl_close($ch);

        $json = json_decode($result);
        
        if(!is_object($json)) {
            throw new Exception(sprintf('BoxBilling API: Invalid Response "%s"', $result));
        }

        if(isset($json->error) && !empty($json->error)) {
            throw new Exception(sprintf('BoxBilling API method "%s" returned error: "%s"', $method, $json->error->message), $json->error->code);
        }

        if(!isset($json->result)) {
            throw new Exception(sprintf('BoxBilling API: Invalid Response "%s"', $result));
        }

        return $json->result;
    }

}
```
And the code I'm running on `support.php` is this:
```
require_once('BoxBillingApi.php');
            $config = array(
                'api_role'  =>  'guest',
                'api_url'   =>  'https://path.to.boxbilling/api',
            );
            $api_guest = new Service_BoxBilling($config);
            print $api_guest->system_version();
```

I'm really stuck. Thank you in advance. _I'm sorry if I posted this in the wrong place._

**Comment by 4Giedrius** [comment]
No worries, this is the right place to ask. I see that you are using `https` and it seems that cURL needs SSL verification. Please try adding following line to your code and let us know if it fixes your problem:

`curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);`

P.S. Our latest version is v4.16.3, you can always find newest releases [here](https://github.com/boxbilling/boxbilling/releases/latest).

**Comment by Dylan3304** [comment]
Okay, if I add that line I get a new **error:**
```
Fatal error: Uncaught exception 'Exception' with message 'Curl Error: "Cannot communicate securely with peer: no common encryption algorithm(s)."' in strip/BoxBillingApi.php:84 Stack trace: #0 strip/support.php(32): Service_BoxBilling->__call('system_version', Array) #1 strip/support.php(32): Service_BoxBilling->system_version() #2 {main} thrown in strip/BoxBillingApi.php on line 84
```
**However, if I change `CURLOPT_SSL_VERIFYPEER` to true, then I receive this:**
```
Fatal error: Uncaught exception 'Exception' with message 'Curl Error: ""' in strip/BoxBillingApi.php:84 Stack trace: #0 strip/support.php(32): Service_BoxBilling->__call('system_version', Array) #1 strip/support.php(32): Service_BoxBilling->system_version() #2 {main} thrown in strip/BoxBillingApi.php on line 84
```
_Thank you for your assistance._

**Comment by 4Giedrius** [comment]
It seems like there is an issue with your SSL certificate. Could you try to connect to API without certificate and let us know if it works.

**Comment by Dylan3304** [comment]
Okay using HTTP now. I now get this error:
```
Fatal error: Uncaught exception 'Exception' with message 'BoxBilling API: Invalid Response "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>302 Found</title> <script type="text/javascript"> //<![CDATA[ try{if (!window.CloudFlare) {var CloudFlare=[{verbose:0,p:1429924034,byc:0,owlid:"cf",bag2:1,mirage2:0,oracle:0,paths:{cloudflare:"/cdn-cgi/nexp/dok3v=1613a3a185/"},atok:"6c4cda93ea65d22a46fc30ec4afa6e6b",petok:"003cc672c4bcad6f661b40528b6194f6b63983d2-1431031378-1800",zone:"example.com",rocket:"a",apps:{"abetterbrowser":{"ie":"7","opera":null,"chrome":null,"safari":null,"firefox":null}}}];CloudFlare.push({"apps":{"ape":"5b09d5da20e7293afa1ad918ec119c7c"}});document.write('<script type="text/javascript" src="//ajax.cloudflare.com/cdn-cgi/nexp/dok3v=7e13c32551/cloudflare.min.js"><'+'\/script>');}}catch(e){}; //]]> </script> </head><body> <h1>Found</h1> <p>The document has moved <a href="https://boxbilling.com/api/guest/system/version">here</a>.</p> </body></html> "' in stripe/BoxBillingApi.php on line 94
```
**Thank you once again.**

**Comment by 4Giedrius** [comment]
Could you open ticket from members area and provide URL you are trying to connect?

**Comment by 4Giedrius** [comment]
Is your website where BoxBiling is installed, protected by CloudFlare? It looks like [I'm Under Attack Mode](https://blog.cloudflare.com/introducing-im-under-attack-mode/) feature of CloudFlare is blocking access to API for you.

**Comment by Dylan3304** [comment]
I use CloudFlare, but I don't think I'm in 'I'm under attack mode'. I'm unfortunately migrating away from BoxBilling. However, I wish you and the team best of luck!
