### ISSUE TITLE
503 Service Unavailable The server is temporarily busy, try again later!

### ISSUE THREAD

**Issue by Hosting24pw** [boxbilling/boxbilling#521]
Hello,

When I try to open my website shopping cart it gives  message "503 Service Unavailable The server is temporarily busy, try again later!". In log files like this: 

[28-Jul-2018 04:53:47 UTC] PHP Stack trace:
[28-Jul-2018 04:53:47 UTC] PHP   1. {main}() /home/public_html/cart/index.php:0
[28-Jul-2018 04:53:47 UTC] PHP   2. require_once() /home/public_html/cart/index.php:13
[28-Jul-2018 04:53:47 UTC] PHP   3. date_default_timezone_set() /home/public_html/cart/bb-load.php:110
[28-Jul-2018 04:53:47 UTC] 8 date_default_timezone_set(): Timezone ID 'BST' is invalid /home/public_html/cart/bb-load.php 110
[28-Jul-2018 04:53:47 UTC] PHP Notice:  date_default_timezone_set(): Timezone ID 'BST' is invalid in /home/public_html/cart/bb-load.php on line 110

Anyone can give suggestions to solve it?

**Comment by Eiskaltereistee** [comment]
Hi,

I think the timezone is not the fatal error, it's just a notice. But maybe you should fix that anyway.
Maybe you can share you like 110 in /home/public_html/cart/bb-load.php

For further debugging:
- Please enable the debug mode in your bb-config.php
- Please check your apache (/var/log/apache2/error_log) or nginx error log (/var/log/nginx/error_log
- Check your bb-logs folder too: src/bb-data/log/php_error.log

Also you should share your PHP and MySql Version.

Have a nice day!

**Comment by Hosting24pw** [comment]
Hi,

My website url is: https://www.hosting24.pw/cart

PHP Version is: 6.6.30, Database client version: libmysql: 5.1.73

php error log is: 
[28-Jul-2018 13:00:02 UTC] Error executing massmailer queue: Queue not found
[28-Jul-2018 13:11:54 UTC] Unable to find template "mod_page_contact.php" (looked into: /home/public_html/cart/bb-themes/boxbilling/html, /home/public_html/cart/bb-modules/Page/html_client).
[28-Jul-2018 13:11:54 UTC] exception 'Box_Exception' with message 'Page not found' in /home/public_html/cart/bb-library/Box/AppClient.php:72
Stack trace:
#0 /home/public_html/cart/bb-library/Box/AppClient.php(56): Box_AppClient->render('mod_page_contac...', Array, 'php')
#1 [internal function]: Box_AppClient->get_custom_page('contact.php')
#2 /home/public_html/cart/bb-library/Box/App.php(220): ReflectionMethod->invokeArgs(Object(Box_AppClient), Array)
#3 /home/public_html/cart/bb-library/Box/App.php(259): Box_App->execute('get_custom_page', Array)
#4 /home/public_html/cart/bb-library/Box/App.php(143): Box_App->processRequest()
#5 /home/public_html/cart/index.php(27): Box_App->run()
#6 {main}
[28-Jul-2018 13:11:54 UTC] Page contact not found

**Comment by Eiskaltereistee** [comment]
Hi,

it looks like there is a template missing: `Unable to find template "mod_page_contact.php" (looked into: /home/public_html/cart/bb-themes/boxbilling/html, /home/public_html/cart/bb-modules/Page/html_client)`

Please check, that the template is located in one of that paths. If not, please upload the latest release again.

Also you should known, that there is no php version like 6.6. Do you mean 5.6?

**Comment by Hosting24pw** [comment]
Hi,

The site was working fine upto yesterday. suddenly problem from today.

I have checked, no such file there when install it. I have download the original file from Box billing website and there is no such file there.

**Comment by TuxMay** [comment]
A 503 is a service unavailable message, which is being produced by your hosting server, have your contacted your hosting provider regarding this issue? If your site is producing this error but another site on the same server is not, then it usually means there is not enough resources on the server to maintain your site - if all sites are down, this may be a cPanel/WHM miss-configuration or a site trying to hog a resource (a poor coded script/module - like a hacked WHMCS or resource intensive script like a custom coded module).
